#!/bin/bash

usage() {
        echo "Usage: $0  [test suite file] [test program file]"  1>&2
        exit 1
}

if [ ${#} -ne 2 ]; then
        usage
fi

for test in `cat "$1"`; do
	if [ -r "$test".in ]; then
        	if [ -r "$test".args ]; then
			"${2}" `cat "$test".args` < "$test".in  > "$test".out
		else
                        "${2}" < "$test".in  > "$test".out
		fi	
	else 
		if [ -r "$test".args ]; then
			"${2}" `cat "$test".args` > "$test".out
		else
			"${2}" > "$test".out	
		fi
	fi
done
